### ISSUE TITLE
Version 1.80.1 is not working

### ISSUE THREAD

**Issue by BennyBrowns** [microsoft/vsts-extension-retrospectives#371]
Hi team,

The plugin stopped working after the automatic update yesterday to 1.80.1 (Latest).
The loading bar keeps showing and different errors are logged in the browser console (e.g. CORS).

![image](https://user-images.githubusercontent.com/108653348/177097570-76effad3-3ee1-4f0c-9592-f6e2261aa932.png)

Can you please check this? Thank you very much!

Kind regards.

**Comment by Jegge** [comment]
Same problem here. We use the plugin on a local installation and it thinks that it's backend service URL is https://app-retrospective-extension-prod.azurewebsites.net. Shouldn't this be our local server?

**Comment by danielabreu-cotacao** [comment]
Same problem here.

**Comment by IRQG** [comment]
Hi, I'm experiencing the same problem on Azure on premise 2019. Error from js console 
 _Access to fetch at 'https://app-retrospective-extension-prod.azurewebsites.net/collaborationUpdates/negotiate?negotiateVersion=1' from origin '<my server url was here>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

**Comment by gabrielgdomingos** [comment]
Same problem.

**Comment by shariqueshueb** [comment]
Same problem

**Comment by TejalVV** [comment]
Has anyone found the solution ?

**Comment by danielabreu-cotacao** [comment]
I did a rollback on my environment.

**Comment by kpworld** [comment]
> I did a rollback on my environment.

What type of rollback?  a full rollback or of the extension itself? Haven't seen a way to do a rollback of one of MS built extensions or the best way to accomplish that.   Any help is appreciated.

**Comment by danielabreu-cotacao** [comment]
I downloaded the old version on this url: https://marketplace.visualstudio.com/_apis/gallery/publishers/ms-devlabs/extensions/team-retrospectives/1.70.6/package?noPrompt=true, opened the file with 7zip and changed the version inside the file extension.vsixmanifest to a version above the current one. After that updated manually Azure DevOps with this "new" version.

**Comment by polatengin** [comment]
hi @BennyBrowns , @Jegge , @danielabreu-cotacao , @Yozya , @IRQG , @kpworld , @gabrielgdomingos , @shariqueshueb , @TejalVV 

first of all, sorry for the inconvenience, I wasn't expect to have an issue with the sync service.

I was testing and playing with the new version on my dev environment for a quite time.

I just fixed (at least I think I fixed) the issues, and, release a new version (v1.80.4) to the production environment.

I'll keep this issue open for a week, to collect the feedbacks, hopefully there will be not much feedbacks 😄

this new version I just released must solve the issues you have.

please let me know, if I can make the extension better anyway.

**Comment by Yozya** [comment]
Still have an error 
"Access to fetch at 'https://app-retrospective-extension-prod.azurewebsites.net/collaborationUpdates/negotiate?negotiateVersion=1' from origin '' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

**Comment by kpworld** [comment]
@pol

> hi @BennyBrowns , @Jegge , @danielabreu-cotacao , @Yozya , @IRQG , @kpworld , @gabrielgdomingos , @shariqueshueb , @TejalVV
> 
> first of all, sorry for the inconvenience, I wasn't expect to have an issue with the sync service.
> 
> I was testing and playing with the new version on my dev environment for a quite time.
> 
> I just fixed (at least I think I fixed) the issues, and, release a new version (v1.80.4) to the production environment.
> 
> I'll keep this issue open for a week, to collect the feedbacks, hopefully there will be not much feedbacks 😄
> 
> this new version I just released must solve the issues you have.
> 
> please let me know, if I can make the extension better anyway.

@polatengin the 1.80.4 version did not fix our issues.   Are you currently looking into further solutions?

**Comment by dstoddar** [comment]
@polatengin

**Comment by BennyBrowns** [comment]
Hi @polatengin. Version 1.80.4 is not working on our environment (on premise server 2019). The same error still occurs. 

Can you recheck this?

Thanks in advance! Kind regards.

**Comment by pollpbl** [comment]
TFS 2018 U3 also doesn't work anymore.
Thanks in advance!

**Comment by denitajc** [comment]
This still isn't working on our TFS 2018 on premise server

**Comment by denitajc** [comment]
> I downloaded the old version on this url: https://marketplace.visualstudio.com/_apis/gallery/publishers/ms-devlabs/extensions/team-retrospectives/1.70.6/package?noPrompt=true, opened the file with 7zip and changed the version inside the file extension.vsixmanifest to a version above the current one. After that updated manually Azure DevOps with this "new" version.

I was not able to get this to work. When I changed the version inside the extension.vsixmanifest to a version above the current one it gave me an error when I tried to update the file about a corrupt manifest. Has anyone else been able to rollback using the method described here?

**Comment by gabrielgdomingos** [comment]
> > I downloaded the old version on this url: https://marketplace.visualstudio.com/_apis/gallery/publishers/ms-devlabs/extensions/team-retrospectives/1.70.6/package?noPrompt=true, opened the file with 7zip and changed the version inside the file extension.vsixmanifest to a version above the current one. After that updated manually Azure DevOps with this "new" version.
> 
> I was not able to get this to work. When I changed the version inside the extension.vsixmanifest to a version above the current one it gave me an error when I tried to update the file about a corrupt manifest. Has anyone else been able to rollback using the method described here?

You should not extract the entire zip, extract only the extension.vsixmanifest file, change the version and then put the edited file in the zip again replacing the current one.
If you want, follow the link to download a version "2.0.0".
https://1drv.ms/u/s!AvnQGG2Tx82sgqwFv6nRBuAJqJt04g?e=4LhtTe

**Comment by denitajc** [comment]
Thank you that worked. I appreciate the quick response.

**Comment by ka-kalee** [comment]
Version 2.0.0 work on ADO 2019.

**Comment by gabrielgdomingos** [comment]
> A versão 2.0.0 funciona no ADO 2019.

Yes, this version 2.0.0 is actually version 1.70.6 masked.

**Comment by kpUniverse** [comment]
Other than rolling back, is there any further progress on resolving the current issue? @polatengin @dstoddar

**Comment by dstoddar** [comment]
@kpUniverse , we are currently debugging. Are you able to upgrade your server? We have not isolated the root cause yet and it's recommended that you upgrade.

**Comment by kpUniverse** [comment]
We are not able to upgrade in the near term. That is a longer term process to complete and not on the radar right now.   

will look to using the downgrade fix above next week if you haven't yet figured out the issue in your debugging.

Thanks!

**Comment by klsgrtx** [comment]
@dstoddar - we are also not in a position to upgrade to ADO 2020.
Running ADO 2019 and have numerous users unhappy about retrospectives not working.

Do you have instructions for rolling back? As we are concerned with possible corruption of data.

**Comment by reavild1** [comment]
My enterprise is among the victims. Did the release that broke this provide so much value that it could not be rolled back?
ADO Server 2019 using http: protocol for DevOps web

**Comment by dstoddar** [comment]
@reavild1 , @klsgrtx , @kpUniverse , @BennyBrowns , @Jegge , @danielabreu-cotacao , @Yozya , @IRQG , @kpworld , @gabrielgdomingos , @shariqueshueb , @TejalVV.

We believe we have isolated and resolved this issue. If you continue to have any issues related to this bug please contact @polatengin directly. Thank you for your patience.

**Comment by gabrielgdomingos** [comment]
> @reavild1 , @klsgrtx , @kpUniverse , @BennyBrowns , @Jegge , @danielabreu-cotacao , @Yozya , @IRQG , @kpworld , @gabrielgdomingos , @shariqueshueb , @TejalVV.
> 
> We believe we have isolated and resolved this issue. If you continue to have any issues related to this bug please contact @polatengin directly. Thank you for your patience.

here solved

**Comment by danielabreu-cotacao** [comment]
here solved too.

**Comment by kpUniverse** [comment]
I'm waiting on it to show up in the system as updated. How long does it normally take?   Or is there a way i can speed that along?  appreciate your efforts at tracking down the issue.  Hoping it fixes ours as well once i can get it in place

@polatengin

**Comment by Yozya** [comment]
@dstoddar @polatengin thank you for your work.

**Comment by kpUniverse** [comment]
The latest showed up and it is working again.  Thanks for working through the problem and providing a solution.   @dstoddar  @polatengin

**Comment by klsgrtx** [comment]
We have deployed the latest (1.80.10) to our 2019 on-prem instance - all appear to be working well.

**Comment by Mi1an** [comment]
We have the version 1.80.11 on our DevOps 2019 and it's still not working. Should we wait for a fix or should we make a downgrade to version 1.80.10?

**Comment by dstoddar** [comment]
> We have the version 1.80.11 on our DevOps 2019 and it's still not working. Should we wait for a fix or should we make a downgrade to the version 1.80.10?

@polatengin , please advise.

**Comment by nordic81** [comment]
We had the same problem, but completely uninstalling and reinstalling the extension did the trick.
Try removing the extension from your collection and removing it from your onprem installation.
Than you can reinstall it via the marketplace and hopefully everything works as expected ;)

**Comment by Mi1an** [comment]
> We had the same problem, but completely uninstalling and reinstalling the extension did the trick. Try removing the extension from your collection and removing it from your onprem installation. Than you can reinstall it via the marketplace and hopefully everything works as expected ;)

Unfortunately this didn't helped us. Retrospectives still not working.
![Screenshot_227](https://user-images.githubusercontent.com/38425854/201899506-ca735173-7fe6-4fd4-857e-fec76acbbe8f.png)

**Comment by KocamanFaruk** [comment]
Hello, 

We are using on-prem Azure Devops 2022.1 RTW. In 1.92.29 version we are getting "CORS Policy" error. 

![Image](https://github.com/user-attachments/assets/233c56a9-c958-4fab-a49e-cb5fa39f8d90)

![Image](https://github.com/user-attachments/assets/d2fe6507-3c02-40a1-9177-40e993eec746)

**Comment by dphanson63** [comment]
An old issue.  Should be resolved.  Related issue should also be resolved.
