### ISSUE TITLE
Retrospective reporting "We detected an error in the application"

### ISSUE THREAD

**Issue by JonFuenningPersonal** [microsoft/vsts-extension-retrospectives#505]
**Describe the bug**
One of our Team Projects hosted in Azure DevOps Servers is encountering the error "We detected an error in the application" when viewing a retrospective for a specific team.   When this occurs, they cannot seem to clear the problem.   I found a work-around by going to a different team project, view an retrospective there, and them coming back to the original team project having problems.   As long as the we view not view the retrospective that triggers the error message, everything works great.

** Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[ x] No

If Yes, what version of the extension?

**To Reproduce**
1. Go to ' https://dev.azure.com/<org>/<team-project>/_apps/hub/ms-devlabs.team-retrospectives.home'
2. Click on '<TeamX> next to Retrospective at top, click on <Retrospective> from drop-down'
3. Scroll down to '....'  N/A
Contents of right frame goes away and is replaced by "We detected an error in the application"

**Expected behavior**
Expected to see retrospective

**Screenshots**
![image](https://user-images.githubusercontent.com/124845386/217683928-5c0b5294-7f1d-4ce6-804d-c0f49b2c1bc9.png)

**What screen type are you seeing this on ?**
[x ] Desktop
[ ] Mobile

**Additional context**

**Comment by polatengin** [comment]
hi, I released a new version with a fix. it seems the extension no longer gives this issue anymore.

**Comment by plynch99** [comment]
I am still seeing this issue occur in one of our ADO projects
