### ISSUE TITLE
retrospective extension Copy link is not working

### ISSUE THREAD

**Issue by ghost** [microsoft/vsts-extension-retrospectives#70]
Copy email query and copy retrospective link is not working as expected .When we click on Copy retrospective link and paste the copied retrospective link on browser it is opening Organization page not the retrospective page. Please fix the issue.

**Comment by cstrempfer** [comment]
This is a duplicate issue as it's already logged here: #50

**Comment by polatengin** [comment]
this issue should be resolved by PR #72

**Comment by EmanMos** [comment]
Can you please re-open this issue, because it is not fixed yet?
What happens now is on this issue: https://github.com/microsoft/vsts-extension-retrospectives/issues/95

**Comment by cstrempfer** [comment]
@EmanMos As this is a duplicate and the behaviour described in #95 was already mentioned in #50, imho it's better to reopen #50, which contains most details.
