### ISSUE TITLE
Projects with more than 255 teams are not showing all teams in the dropdown in Retrospectives

### ISSUE THREAD

**Issue by chandrakanthbala** [microsoft/vsts-extension-retrospectives#755]
**Describe the bug**
We have couple of projects with more than 255 teams. In those projects, the Retrospectives dropdown doesn't show all the teams to select and start a Retro. I looked up the extension code and noticed the extension is getting only top 255 teams. Is there any plan to increase this limit?

Looks like restriction was added here (below URL). 

https://github.com/microsoft/vsts-extension-retrospectives/blob/69011bac51f7bac01892f8ce04b02befe20079f8/RetrospectiveExtension.Frontend/dal/azureDevOpsCoreService.tsx#L53

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[* ] No

**To Reproduce**

1. Open project with more than 255 teams.
2. Open Retrospectives
3. Click team dropdown
4. Not all teams are listed

**Expected behavior**
All teams should be listed

**What screen type are you seeing this on ?**
[ *] Desktop
[ ] Mobile

**Comment by polatengin** [comment]
working on a fix now, I'm planning to release a new version this weekend

**Comment by chandrakanthbala** [comment]
@polatengin Can you please confirm if this fix is released?

**Comment by dphanson63** [comment]
@chandrakanthbala
Is the 255 team limit still an issue?  If you select the option to "Show all teams" under Settings in the upper right menu, do you get different results?
